title:            Joe Sepi
tagline:          Code, Music, Life
description:      I call it home.
# disqus_shortname:
# reading_time:     true
# words_per_minute: 200
#Your site's domain goes here. Leave localhost server or blank when working locally.
url:              http://joesepi.com

# Owner/author information
owner:
  name:           Joe Sepi
  avatar:         IMG_8368_crop3.jpg
  bio:            "Code, Music, Life"
  email:          sepi@joesepi.com
    # Social networking links are used in author-bio sidebar. Update and remove as you like.
  twitter:        joe_sepi
  github:         joesepi
  stackexchange:  joe-sepi
  facebook:       joesepi
  instagram:      joesepi
  tumblr:         joesepi
  linkedin:       joesepi
  flickr:         joesepi
  # For Google Authorship https://plus.google.com/authorship
  # google plus id, include the '+', eg +mmistakes
  google_plus:    +joesepi

# Analytics and webmaster tools stuff goes here
  google_analytics:   #UA-39365944-4
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in top navigation
# For external links add external: true
links:
  - title: Home
    url: /
#  - title: About
#    url: /about/
  - title: Posts
    url: /posts/

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/New_York
future:      true

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:  /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: joesepi

include: [".htaccess"]
exclude: ["lib", "config.rb", "Gemfile", "Capfile", "Gemfile.lock", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]

