title:            Joe Sepi
description:      This the website of Joe Sepi
# disqus_shortname:
# reading_time:     true
# words_per_minute: 200
#Your site's domain goes here. Leave localhost server or blank when working locally.
url:              #http://joesepi.github.io

# Owner/author information
owner:
  name:           Joe Sepi
  avatar:         avatar.jpg
  bio:            "Have you ever wondered about Joe Sepi. Why? Stop that."
  email:          sepi@joesepi.com
    # Social networking links are used in author-bio sidebar. Update and remove as you like.
  twitter:        joe_sepi
  facebook:       joesepi
  github:         joesepi
  stackexchange:  joe-sepi
  linkedin:       joesepi
  instagram:      joesepi
  flickr:         joesepi
  tumblr:         joesepi
  # For Google Authorship https://plus.google.com/authorship
  # google plus id, include the '+', eg +mmistakes
  google_plus:    #+joesepi

# Analytics and webmaster tools stuff goes here
  google_analytics:   #UA-39365944-4
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in top navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Articles
    url: /articles/

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/New_York
future:      true
pygments:    true
markdown:    kramdown

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers:
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfidje", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
